### ISSUE TITLE
[interop layer] cannot query OCONUS locations

### ISSUE THREAD

**Issue by jamestranovich-noaa** [weather-gov/weather.gov#1786]
### Description

If we search for e.g., "Pago Pago" then the API interop layer seems to break. 

stack trace:

```
api-interop-layer-1  | [observations] | warn | observations from PGUM (first choice) are invalid |
api-interop-layer-1  | [observations] | warn | observations from PGUA, PGRO (second and third choice) are invalid |
api-interop-layer-1  | [observations] | warn | No valid observations found for GUM/47/50 |
api-interop-layer-1  | [fetch wrapper] | error |
api-interop-layer-1  | SyntaxError: Unexpected token '<', "<html>
api-interop-layer-1  | <h"... is not valid JSON
api-interop-layer-1  |     at JSON.parse (<anonymous>)
api-interop-layer-1  |     at parseJSONFromBytes (node:internal/deps/undici/undici:5472:19)
api-interop-layer-1  |     at successSteps (node:internal/deps/undici/undici:5454:27)
api-interop-layer-1  |     at fullyReadBody (node:internal/deps/undici/undici:4381:9)
api-interop-layer-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
api-interop-layer-1  |     at async consumeBody (node:internal/deps/undici/undici:5463:7)
api-interop-layer-1  |     at async file:///app/util/fetch.js:18:22
api-interop-layer-1  |     at async default (file:///app/data/satellite.js:8:31)
api-interop-layer-1  |     at async getDataForPoint (file:///app/data/index.js:126:21)
api-interop-layer-1  |     at async Object.handler (file:///app/main.js:49:20)
api-interop-layer-1  | |
```

### Acceptance criteria

- [x] The API interop layer shouldn't break and should return an error message instead

**Comment by eric-gade** [comment]
This appears to have been handled by #1825
